services:
  p2p-news:
    image: ghcr.io/fxhuhn/p2p-news:latest
    pull_policy: always
    container_name: p2p-news
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data
    command: ["scheduler.py"]
