"""
Generiert kuratierte profile.yaml Dateien für alle Plattformen
basierend auf den P2P Empire Erfahrungsberichten und Branchen-Benchmarks.
"""

from pathlib import Path

import yaml

PROFILES = {
    "mintos": {
        "platform": "mintos",
        "platform_name": "Mintos",
        "founding_year": 2015,
        "headquarters": "Riga, Lettland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_mifid",
            "regulator": "Latvijas Banka (Lettische Zentralbank)",
            "license_number": "IBF Lizenz Nr. 06.06.08.719/466",
            "custody": "Segregierte Treuhandkonten bei Tier-1 Banken",
            "investor_compensation": True,
            "contract_structure": "MiFID II Verbriefte Notes (Asset-Backed Securities)",
            "notes": "Europäischer Marktführer, reguliert als Investment Brokerage Firm (IBF) unter MiFID II mit gesetzlichem 20.000 € Anlegerentschädigungsschutz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "AS Mintos Holdings",
            "auditor": "KPMG (unabhängig testiert)",
            "audit_opinion": "Unqualified / Ohne Einschränkung",
            "profitability": "Profitabel im operativen Kern",
            "equity_ratio_pct": 32.0,
            "interest_coverage_ratio": 3.5,
            "notes": "Regelmäßig testierte Konzernabschlüsse durch KPMG (Big-4).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Diversifizierte Konsum-, KFZ- und Agrarkredite",
            "security_type": "Buyback-Garantie + teils Besicherung",
            "ltv_max_pct": None,
            "historical_loss_pct": 1.8,
            "current_npl_pct": 8.0,
            "buyback_grace_period_days": 60,
            "notes": "Über 50 Kreditanbahner weltweit; Altforderungen aus Russland/Ukraine in planmäßiger Recovery.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.85,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 90,
            "withdrawal_queue_days": 0,
            "notes": "Höchste Marktplatz-Liquidität in Europa mit hochaktivem Sekundärmarkt (0,85 % Gebühr).",
        },
        "malus_triggers": {
            "monoculture_pct": 18.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 6.2,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 94.2,
            "lars_wrobbel_score": 34,
            "lars_wrobbel_rank": "Rang 2",
        },
    },
    "lande": {
        "platform": "lande",
        "platform_name": "Lande",
        "founding_year": 2019,
        "headquarters": "Riga, Lettland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_ecsp",
            "regulator": "Latvijas Banka (Lettische Zentralbank)",
            "license_number": "ECSP Lizenz Nr. 27-55/2023/2",
            "custody": "Segregierte Konten bei EU-Kreditinstituten",
            "investor_compensation": False,
            "contract_structure": "Direkte grundbuchliche & dingliche Besicherung",
            "notes": "Regulierte Crowdfunding-Plattform (ECSP) unter Aufsicht der Latvijas Banka.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Lande Finance SIA",
            "auditor": "BDO (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Solide operative Ertragslage im Agrarsektor",
            "equity_ratio_pct": 29.0,
            "interest_coverage_ratio": 3.2,
            "notes": "Stabiles Wachstum mit institutionellen Förderungen (z. B. EIF-Garantien).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Agrarkredite, Erntevorfinanzierung, Landwirtschaftsland",
            "security_type": "1st-Rank Grundbuchhypothek & Agrar-Pfand (Getreide, Maschinen)",
            "ltv_max_pct": 60.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 3.8,
            "buyback_grace_period_days": None,
            "notes": "Strikte dingliche Besicherung im Agrarbereich mit LTV <= 60 % und professionellen Agrar-Gutachten.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 1.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 360,
            "withdrawal_queue_days": 0,
            "notes": "Sekundärmarkt aktiv mit 1 % Gebühr. Tilgungen oft saisonal an Erntezyklen gekoppelt.",
        },
        "malus_triggers": {
            "monoculture_pct": 8.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 8.1,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 91.2,
            "lars_wrobbel_score": 33,
            "lars_wrobbel_rank": "Rang 3",
        },
    },
    "crowdpear": {
        "platform": "crowdpear",
        "platform_name": "Crowdpear",
        "founding_year": 2022,
        "headquarters": "Vilnius, Litauen",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_ecsp",
            "regulator": "Bank of Lithuania (Litauische Zentralbank)",
            "license_number": "ECSP Lizenz Nr. LB002128",
            "custody": "Segregierte Konten bei Paysera",
            "investor_compensation": False,
            "contract_structure": "1st-Rank Hypotheken via litauischen Treuhänder",
            "notes": "Schwesterplattform von PeerBerry, reguliert unter ECSP durch die litauische Zentralbank.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Crowdpear UAB",
            "auditor": "Grant Thornton (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Getragen durch das Gründerteam von PeerBerry",
            "equity_ratio_pct": 38.0,
            "interest_coverage_ratio": 4.0,
            "notes": "Hohe Governance-Standards und enge Verzahnung mit der PeerBerry-Infrastruktur.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Immobilienkredite & Geschäftsentwicklung",
            "security_type": "1st-Rank Hypotheken im Grundbuch",
            "ltv_max_pct": 65.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 2.5,
            "buyback_grace_period_days": None,
            "notes": "Realsicherheiten mit unabhängigen externen Wertgutachten (Ober-Haus).",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 2.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 360,
            "withdrawal_queue_days": 0,
            "notes": "Sekundärmarkt verfügbar mit 2 % Gebühr.",
        },
        "malus_triggers": {
            "monoculture_pct": 15.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 8.5,
            "p2p_empire_safety_band": "Hoch",
            "p2p_empire_portfolio_perf": 90.1,
            "lars_wrobbel_score": 33,
            "lars_wrobbel_rank": "Rang 3",
        },
    },
    "twino": {
        "platform": "twino",
        "platform_name": "Twino",
        "founding_year": 2015,
        "headquarters": "Riga, Lettland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_mifid",
            "regulator": "Latvijas Banka (Lettische Zentralbank)",
            "license_number": "IBF Lizenz Nr. 06.06.08.721/468",
            "custody": "Segregierte Treuhandkonten bei EU-Kreditinstituten",
            "investor_compensation": True,
            "contract_structure": "MiFID II Verbriefte Notes",
            "notes": "Lizenzierte Wertpapierfirma (IBF) unter Aufsicht der Latvijas Banka mit gesetzlichem Entschädigungsschutz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "AS TWINO",
            "auditor": "BDO (unabhängig testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Langjährig etablierter Plattform- und Kreditbetrieb",
            "equity_ratio_pct": 27.0,
            "interest_coverage_ratio": 2.9,
            "notes": "Unabhängig testierte Jahresabschlüsse durch BDO.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Kurzfristige Konsumentenkredite (Polen, Lettland, Vietnam)",
            "security_type": "60-Tage Rückkaufgarantie der Twino-Gruppe",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.8,
            "current_npl_pct": 4.2,
            "buyback_grace_period_days": 60,
            "notes": "Verlässliche Rückkaufgarantie für reguläre Notes.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 60,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt, jedoch kurze originäre Kreditlaufzeiten (1 bis 3 Monate).",
        },
        "malus_triggers": {
            "monoculture_pct": 85.0,  # Twino Group stellt den Großteil des Volumens
            "monoculture_originator": "TWINO Gruppe",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 6.2,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 96.5,
            "lars_wrobbel_score": 30,
            "lars_wrobbel_rank": "Rang 5",
        },
    },
    "indemo": {
        "platform": "indemo",
        "platform_name": "Indemo",
        "founding_year": 2023,
        "headquarters": "Riga, Lettland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_mifid",
            "regulator": "Latvijas Banka (Lettische Zentralbank)",
            "license_number": "IBF Lizenz Nr. 27-55/2023/1",
            "custody": "Segregierte Konten bei Signet Bank / Tier-1",
            "investor_compensation": True,
            "contract_structure": "MiFID II Verbriefte Notes (Discounted Debt)",
            "notes": "Voll lizenzierte Wertpapierfirma (IBF) unter Aufsicht der Latvijas Banka mit 20.000 € Anlegerentschädigungsschutz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "SIA Indemo",
            "auditor": "BDO (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Erfahrenes Managementteam aus Ex-Twino Führungskräften",
            "equity_ratio_pct": 33.0,
            "interest_coverage_ratio": 3.6,
            "notes": "Erfüllt alle Eigenkapitalanforderungen der MiFID II Aufsicht.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Diskontierte Hypothekenschulden (Discounted Debt Investments - DDI) & Immobilien",
            "security_type": "1st-Rank Hypotheken in Spanien mit vertraglichem 40-50 % Diskont",
            "ltv_max_pct": 50.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 0.0,
            "buyback_grace_period_days": None,
            "notes": "Hoher Puffer durch 40-50 % Diskont auf den Marktwert erststelliger spanischer Wohnimmobilien.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 360,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt; Erlöse fließen bei Verwertung oder Refinanzierung der Bankforderungen zu.",
        },
        "malus_triggers": {
            "monoculture_pct": 20.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 8.8,
            "p2p_empire_safety_band": "Hoch",
            "p2p_empire_portfolio_perf": 97.3,
            "lars_wrobbel_score": 27,
            "lars_wrobbel_rank": "Rang 8",
        },
    },
    "income": {
        "platform": "income",
        "platform_name": "Income Marketplace",
        "founding_year": 2020,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated_with_pipeline",
            "regulator": "Finantsinspektsioon (in Lizenzierungsverfahren)",
            "license_number": None,
            "custody": "Segregierte Treuhandkonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge mit Junior Share & Cashflow Buffer",
            "notes": "Operiert derzeit unreguliert über Abtretungsverträge, bietet aber institutionelle Schutzmechanismen (Junior Share, Cashflow Buffer).",
        },
        "governance_and_solvency": {
            "guarantor_group": "Income Company OÜ",
            "auditor": "Grant Thornton (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Erfahrenes Gründerteam um Kimmo Rytkönen",
            "equity_ratio_pct": 26.0,
            "interest_coverage_ratio": 3.0,
            "notes": "Testierte Finanzberichte und hohe Transparenz bei Anbahner-Bilanzen.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Konsum-, KFZ- und Unternehmenskredite",
            "security_type": "Buyback-Garantie + Cashflow Buffer + Junior Share",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 2.8,
            "buyback_grace_period_days": 60,
            "notes": "Innovativer Junior Share Mechanismus: Kreditanbahner trägt erste Verluste vor Anlegern.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 90,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt, Liquidität über kurze originäre Kreditlaufzeiten.",
        },
        "malus_triggers": {
            "monoculture_pct": 25.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 8.1,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 98.0,
            "lars_wrobbel_score": 25,
            "lars_wrobbel_rank": "Rang 9",
        },
    },
    "robocash": {
        "platform": "robocash",
        "platform_name": "Robocash",
        "founding_year": 2017,
        "headquarters": "Zagreb, Kroatien",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Getrennte Firmenkonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge (Assignment)",
            "notes": "Unreguliert über Kroatien operierend.",
        },
        "governance_and_solvency": {
            "guarantor_group": "UnaFinancial Holding (Singapur)",
            "auditor": "KPMG (testierter Konzernabschluss)",
            "audit_opinion": "Unqualified",
            "profitability": "UnaFinancial hochprofitabel in Asien (Philippinen, Kasachstan)",
            "equity_ratio_pct": 24.0,
            "interest_coverage_ratio": 3.1,
            "notes": "Mutterkonzern UnaFinancial profitabel, jedoch Klumpen in volatilen Schwellenländern und historische Russland-Wurzeln.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Kurzfristige Konsumkredite (Payday Loans)",
            "security_type": "30-Tage Buyback-Garantie der UnaFinancial",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 1.5,
            "buyback_grace_period_days": 30,
            "notes": "0 % historischer Kapitalverlust für Anleger; 30-Tage Rückkauffrist.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 30,
            "withdrawal_queue_days": 0,
            "notes": "Sehr hohe Liquidität durch 30-Tage-Kurzläufer und gebührenfreien Sekundärmarkt.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,  # 100 % Abhängigkeit von UnaFinancial!
            "monoculture_originator": "UnaFinancial Holding",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 4.6,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": 28,
            "lars_wrobbel_rank": "Rang 7",
        },
    },
    "fintown": {
        "platform": "fintown",
        "platform_name": "Fintown",
        "founding_year": 2023,
        "headquarters": "Prag, Tschechien",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Firmenkonten bei tschechischen Banken",
            "investor_compensation": False,
            "contract_structure": "Nachrangige Darlehen / Abtretungen",
            "notes": "Unreguliert nach tschechischem Recht.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Vihorev Group",
            "auditor": "Lokaler Wirtschaftsprüfer",
            "audit_opinion": "Standard",
            "profitability": "Ertragreich durch touristische Kurzzeitvermietung in Prag",
            "equity_ratio_pct": 22.0,
            "interest_coverage_ratio": 2.5,
            "notes": "100 % Abhängigkeit von der Vihorev Group (Immobilienentwickler in Prag).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Mietimmobilien und Serviced Apartments in Prag",
            "security_type": "Mezzanine / Qualifizierter Nachrang auf Mieteinnahmen",
            "ltv_max_pct": 75.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 0.0,
            "buyback_grace_period_days": None,
            "notes": "Keine erstrangige Grundschuld für Privatanleger; Kredite sind qualifiziert nachrangig.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 10.0,  # Früher Ausstieg mit hohem Abschlag (bis 10 %)
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 720,
            "withdrawal_queue_days": 0,
            "notes": "Kapital ist langjährig gebunden; vorzeitiger Ausstieg nur mit empfindlichem Abschlag.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,
            "monoculture_originator": "Vihorev Group",
            "term_mismatch": True,  # Verspricht flexible Liquidität / tägliche Zinsen auf illiquide Hotelimmobilien
            "term_mismatch_detail": "Tägliche Zinsauszahlung versprochen, aber durch langfristige Hotelimmobilien hinterlegt.",
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 7.3,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": 19,
            "lars_wrobbel_rank": "Rang 13",
        },
    },
    "monefit": {
        "platform": "monefit",
        "platform_name": "Monefit SmartSaver",
        "founding_year": 2022,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Betriebskonten der Creditstar Group",
            "investor_compensation": False,
            "contract_structure": "Unbesicherte Darlehen an Creditstar Tochter",
            "notes": "Völlig unreguliertes Produkt; keine Einlagensicherung, keine Treuhandkonten.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Creditstar Group AS",
            "auditor": "KPMG (verzögerte Berichterstattung)",
            "audit_opinion": "Mit Hinweisen zur Refinanzierung",
            "profitability": "Creditstar unter hohem Refinanzierungsdruck (Anleihen-Fälligkeiten)",
            "equity_ratio_pct": 16.0,
            "interest_coverage_ratio": 1.4,
            "notes": "Erhebliche Einreichungsverzögerungen bei Bilanzen; Pending Payments auf Mintos und Lendermarket.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Unbesicherte Konsumentenkredite",
            "security_type": "Creditstar Rückkaufversprechen",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 12.0,
            "buyback_grace_period_days": None,
            "notes": "Völlig unbesichert; Rückzahlung hängt allein von der Solvenz der Creditstar Group ab.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 30,
            "withdrawal_queue_days": 10,  # Warteschlangen bei Auszahlungen
            "notes": "Verspricht tägliche Auszahlung (Tagesgeld-Ähnlich), geriet jedoch wiederholt in Auszahlungsverzug.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,
            "monoculture_originator": "Creditstar Group AS",
            "term_mismatch": True,
            "term_mismatch_detail": "Tägliche/flexible Auszahlung versprochen, aber durch langlaufende, illiquide Kredite hinterlegt.",
            "related_party_opacity": True,
            "related_party_detail": "Plattform dient rein der Refinanzierung des Schwesterkonzerns Creditstar.",
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 0.0,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 70.0,
            "lars_wrobbel_score": 16,
            "lars_wrobbel_rank": "Rang 14",
        },
    },
    "capitalia": {
        "platform": "capitalia",
        "platform_name": "Capitalia",
        "founding_year": 2007,
        "headquarters": "Riga, Lettland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_ecsp",
            "regulator": "Latvijas Banka (Lettische Zentralbank)",
            "license_number": "ECSP Lizenz Nr. 27-55/2023/4",
            "custody": "Segregierte Treuhandkonten",
            "investor_compensation": False,
            "contract_structure": "Besicherte Unternehmenskredite & Mezzanine",
            "notes": "ECSP-lizenziert unter Aufsicht der Latvijas Banka.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Capitalia SE",
            "auditor": "BDO (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Seit über 15 Jahren profitabler KMU-Finanzierer im Baltikum",
            "equity_ratio_pct": 36.0,
            "interest_coverage_ratio": 4.1,
            "notes": "Langjährig bewährtes Managementteam; Co-Investments mit der Europäischen Investitionsbank.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Mittelständische Unternehmenskredite & Wachstumsfinanzierung",
            "security_type": "Gewerbliche Grundschulden, Bürgschaften, Forderungsabtretungen",
            "ltv_max_pct": 65.0,
            "historical_loss_pct": 1.2,
            "current_npl_pct": 2.1,
            "buyback_grace_period_days": None,
            "notes": "Dinglich besichert mit institutioneller Due-Diligence.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 540,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt; planbare Rückzahlung über 12 bis 36 Monate.",
        },
        "malus_triggers": {
            "monoculture_pct": 15.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 6.9,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": 33,
            "lars_wrobbel_rank": "Rang 3",
        },
    },
    "afranga": {
        "platform": "afranga",
        "platform_name": "Afranga",
        "founding_year": 2021,
        "headquarters": "Sofia, Bulgarien",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_ecsp",
            "regulator": "Bulgarische Finanzaufsicht (FSC) / ECSP",
            "license_number": "ECSP Lizenz RG-05-0275",
            "custody": "Segregierte Treuhandkonten",
            "investor_compensation": False,
            "contract_structure": "ECSP regulierte Kredite",
            "notes": "Regulierte paneuropäische Crowdfunding-Plattform (ECSP).",
        },
        "governance_and_solvency": {
            "guarantor_group": "Stik Credit AD",
            "auditor": "BDO (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Stik Credit profitabel im bulgarischen Konsumentenkreditmarkt",
            "equity_ratio_pct": 29.0,
            "interest_coverage_ratio": 3.2,
            "notes": "Testierter Jahresabschluss der Stik Credit Gruppe.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Verbraucherkredite in Bulgarien",
            "security_type": "60-Tage Buyback-Garantie der Stik Credit",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 3.0,
            "buyback_grace_period_days": 60,
            "notes": "Konsumkredite mit verlässlichem Rückkaufversprechen.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 90,
            "withdrawal_queue_days": 0,
            "notes": "Gebührenfreier Sekundärmarkt und kurze originäre Kreditlaufzeiten.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,  # 100 % Abhängigkeit von Stik Credit
            "monoculture_originator": "Stik Credit AD",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 7.3,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": 21,
            "lars_wrobbel_rank": "Rang 11",
        },
    },
    "bondora": {
        "platform": "bondora",
        "platform_name": "Bondora",
        "founding_year": 2008,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "national",
            "regulator": "Finantsinspektsioon (Estnische Kreditgeber-Lizenz)",
            "license_number": "Lizenz 4.1-1/23",
            "custody": "Konten bei estnischen Banken (keine MiFID II Segregation)",
            "investor_compensation": False,
            "contract_structure": "Forderungsabtretung / Go & Grow Sammelpool",
            "notes": "National lizenziert als Kreditgeber in Estland; kein Wertpapierinstitut, kein gesetzlicher 20k Entschädigungsschutz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Bondora Group AS",
            "auditor": "KPMG (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Seit vielen Jahren hochprofitabel, signifikante Gewinnausschüttungen",
            "equity_ratio_pct": 34.0,
            "interest_coverage_ratio": 4.5,
            "notes": "Konzernabschluss unabhängig durch KPMG testiert; solide Profitabilität.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Ungesicherte Konsumentenkredite (Estland, Finnland, Spanien, Niederlande)",
            "security_type": "Keine dingliche Sicherheit, kein formeller Buyback",
            "ltv_max_pct": None,
            "historical_loss_pct": 4.5,
            "current_npl_pct": 18.0,
            "buyback_grace_period_days": None,
            "notes": "Konsumentenkredite mit strukturellen Ausfällen; Go & Grow puffert diese über Renditeabstand ab.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 720,  # Konsumkredite laufen 2-5 Jahre
            "withdrawal_queue_days": 0,
            "notes": "Go & Grow verspricht tägliche Verfügbarkeit, behält sich jedoch vertraglich Teilabhebungen im Krisenfall vor.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,
            "monoculture_originator": "Bondora AS",
            "term_mismatch": True,  # Go & Grow Mismatch
            "term_mismatch_detail": "Tägliche Verfügbarkeit versprochen, aber durch langlaufende unbesicherte Konsumkredite (bis 5 Jahre) hinterlegt.",
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 6.9,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 72.6,
            "lars_wrobbel_score": 25,
            "lars_wrobbel_rank": "Rang 9",
        },
    },
    "swaper": {
        "platform": "swaper",
        "platform_name": "Swaper",
        "founding_year": 2016,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Betriebskonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge",
            "notes": "Völlig unreguliert über Estland operierend.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Wandoo Finance Group",
            "auditor": None,
            "audit_opinion": "Ungeprüft",
            "profitability": "Intransparente Finanzberichterstattung",
            "equity_ratio_pct": None,
            "interest_coverage_ratio": None,
            "notes": "Keine unabhängig testierten Konzernberichte öffentlich verfügbar (Vorsichtsprinzip).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Konsumkredite (Polen, Spanien)",
            "security_type": "30-Tage Buyback-Garantie der Wandoo Finance",
            "ltv_max_pct": None,
            "historical_loss_pct": 1.0,
            "current_npl_pct": 6.0,
            "buyback_grace_period_days": 30,
            "notes": "Konsumkredite gestützt auf Rückkaufversprechen der Wandoo Finance.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 30,
            "withdrawal_queue_days": 0,
            "notes": "Hohe Fungibilität durch 30-Tage-Kredite und Sekundärmarkt.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,
            "monoculture_originator": "Wandoo Finance Group",
            "term_mismatch": False,
            "related_party_opacity": True,
            "related_party_detail": "Fehlende testierte Jahresabschlüsse und Intransparenz der Holding-Eigentümer.",
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 1.1,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 80.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "lendermarket": {
        "platform": "lendermarket",
        "platform_name": "Lendermarket",
        "founding_year": 2019,
        "headquarters": "Dublin, Irland / Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Firmenkonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge",
            "notes": "Unregulierter Marktplatz; keine Segregation durch lizenziertes Institut.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Creditstar Group AS",
            "auditor": "KPMG (mit Einschränkungen)",
            "audit_opinion": "Erhöhte Refinanzierungsrisiken",
            "profitability": "Creditstar unter hohem Liquiditätsdruck",
            "equity_ratio_pct": 17.0,
            "interest_coverage_ratio": 1.5,
            "notes": "Chronische Pending Payments bei Creditstar-Krediten über viele Monate.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Konsumentenkredite (Spanien, Finnland, Estland)",
            "security_type": "60-Tage Rückkaufgarantie",
            "ltv_max_pct": None,
            "historical_loss_pct": 3.5,
            "current_npl_pct": 22.0,  # Erhebliche Pending Payments
            "buyback_grace_period_days": 60,
            "notes": "Rückkaufgarantie wurde in der Vergangenheit wiederholt ausgesetzt oder verzögert bedient.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 360,
            "withdrawal_queue_days": 14,
            "notes": "Kein Sekundärmarkt; erhebliche Auszahlungsverzögerungen bei fälligen Geldern.",
        },
        "malus_triggers": {
            "monoculture_pct": 65.0,  # Hohe Creditstar-Abhängigkeit
            "monoculture_originator": "Creditstar Group AS",
            "term_mismatch": False,
            "related_party_opacity": True,
            "related_party_detail": "Verflechtung zwischen Lendermarket-Betreibern und Creditstar Management.",
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 5.8,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 78.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "bondster": {
        "platform": "bondster",
        "platform_name": "Bondster",
        "founding_year": 2017,
        "headquarters": "Prag, Tschechien",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Firmenkonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge",
            "notes": "Unregulierter tschechischer P2P-Marktplatz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "CEP Invest / Verschiedene Kreditanbahner",
            "auditor": "Lokaler Prüfer",
            "audit_opinion": "Gemischt",
            "profitability": "Betreibergesellschaft stabil, aber schwache Anbahnerqualität",
            "equity_ratio_pct": 19.0,
            "interest_coverage_ratio": 2.0,
            "notes": "Wiederholte Ausfälle externer Kreditanbahner (Right Choice, Lime, EuroGroshi).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Konsum-, KFZ- und Unternehmenskredite",
            "security_type": "Buyback-Garantie der einzelnen Anbahner",
            "ltv_max_pct": None,
            "historical_loss_pct": 4.8,
            "current_npl_pct": 15.0,
            "buyback_grace_period_days": 60,
            "notes": "Ausfallquote überdurchschnittlich hoch; zersplitterter Workout-Prozess.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 180,
            "withdrawal_queue_days": 0,
            "notes": "Gebührenfreier Sekundärmarkt vorhanden.",
        },
        "malus_triggers": {
            "monoculture_pct": 25.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 0.0,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 65.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "revest": {
        "platform": "revest",
        "platform_name": "Revest",
        "founding_year": 2022,
        "headquarters": "Wien, Österreich / Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Betriebskonten",
            "investor_compensation": False,
            "contract_structure": "Nachrangdarlehen",
            "notes": "Unreguliert nach estnischem/österreichischem Recht.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Revest Group",
            "auditor": "Lokaler Prüfer",
            "audit_opinion": "Standard",
            "profitability": "Junges Unternehmen, Immobilienentwicklung",
            "equity_ratio_pct": 20.0,
            "interest_coverage_ratio": 2.2,
            "notes": "Eigentümergeführtes Immobilien-Startup.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Immobilienprojekte in Österreich und Spanien",
            "security_type": "Nachrangige Grundschulden oder Mezzanine",
            "ltv_max_pct": 72.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 0.0,
            "buyback_grace_period_days": None,
            "notes": "Immobilienentwicklungsprojekte mit höherem Fertigstellungsrisiko.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 540,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt, Kapital bis zur Projektfertigstellung gebunden.",
        },
        "malus_triggers": {
            "monoculture_pct": 80.0,
            "monoculture_originator": "Revest Group",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 5.4,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "ventus": {
        "platform": "ventus",
        "platform_name": "Ventus Energy",
        "founding_year": 2023,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Betriebskonten",
            "investor_compensation": False,
            "contract_structure": "Unternehmensanleihen / Kredite",
            "notes": "Unregulierter Energie-Crowdfunder.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Ventus Energy OÜ",
            "auditor": None,
            "audit_opinion": "Ungeprüft",
            "profitability": "Akute finanzielle Schieflage / Restrukturierung",
            "equity_ratio_pct": None,
            "interest_coverage_ratio": None,
            "notes": "Zahlungsstopps und laufende Sanierungsverhandlungen mit Gläubigern.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Erneuerbare Energieprojekte (Biogas, Wind)",
            "security_type": "Unternehmensbürgschaft / Projektrechte",
            "ltv_max_pct": None,
            "historical_loss_pct": 12.0,
            "current_npl_pct": 65.0,  # Akute Notlage
            "buyback_grace_period_days": None,
            "notes": "Projekte in Verzug oder gerichtlich anhängig.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 720,
            "withdrawal_queue_days": 30,  # Auszahlungen blockiert
            "notes": "Auszahlungen de facto gestoppt oder blockiert.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,
            "monoculture_originator": "Ventus Energy",
            "term_mismatch": False,
            "related_party_opacity": True,
            "related_party_detail": "Intransparente Mittelverwendung und verweigerte Gutachten.",
            "distressed_workout": True,
            "distressed_notes": "Akutes Sanierungsverfahren, Auszahlungsstopps, 65 % NPL.",
        },
        "benchmarks": {
            "p2p_empire_safety_score": 0.0,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 50.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "loanch": {
        "platform": "loanch",
        "platform_name": "Loanch",
        "founding_year": 2023,
        "headquarters": "Vilnius, Litauen",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated",
            "regulator": None,
            "license_number": None,
            "custody": "Firmenkonten",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge",
            "notes": "Unregulierter Marktplatz.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Loanch UAB / Asiatische Kreditgeber",
            "auditor": None,
            "audit_opinion": "Ungeprüft",
            "profitability": "Sehr junges Startup",
            "equity_ratio_pct": None,
            "interest_coverage_ratio": None,
            "notes": "Keine testierten Finanzberichte vorhanden (Vorsichtsprinzip).",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Konsumkredite aus Südostasien (Indonesien, Sri Lanka)",
            "security_type": "30-Tage Buyback-Garantie der Anbahner",
            "ltv_max_pct": None,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 2.0,
            "buyback_grace_period_days": 30,
            "notes": "Unbesicherte Kredite in Schwellenländern mit Währungsrisiko.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": True,
            "secondary_market_fee_pct": 0.0,
            "secondary_market_waiting_days": 0,
            "primary_loan_duration_days_avg": 30,
            "withdrawal_queue_days": 0,
            "notes": "Kurzläufer-Kredite mit gebührenfreiem Sekundärmarkt.",
        },
        "malus_triggers": {
            "monoculture_pct": 60.0,
            "monoculture_originator": "Hauptanbahner",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 0.0,
            "p2p_empire_safety_band": "Niedrig",
            "p2p_empire_portfolio_perf": 90.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "modena": {
        "platform": "modena",
        "platform_name": "Modena",
        "founding_year": 2023,
        "headquarters": "Tallinn, Estland",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "unregulated_with_pipeline",
            "regulator": "Finantsinspektsioon (in Vorbereitung)",
            "license_number": None,
            "custody": "Treuhandkonten bei estnischen Banken",
            "investor_compensation": False,
            "contract_structure": "Abtretungsverträge mit Fahrzeug-Sicherheiten",
            "notes": "Estnisches Fintech, unreguliert über Abtretungsverträge.",
        },
        "governance_and_solvency": {
            "guarantor_group": "Modena Mobility OÜ",
            "auditor": "Grant Thornton (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Profitabel im estnischen KFZ-Leasingmarkt",
            "equity_ratio_pct": 31.0,
            "interest_coverage_ratio": 3.8,
            "notes": "Finanziell solide aufgestellt mit Fokus auf Mobilitätsfinanzierung.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "KFZ-Finanzierung und Fahrzeug-Leasing",
            "security_type": "Fahrzeugbrief-Eintrag / Eigentumsvorbehalt (Mobiliarsicherheit)",
            "ltv_max_pct": 70.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 1.5,
            "buyback_grace_period_days": 60,
            "notes": "Dinglich besichert über Fahrzeugpfandrechte im estnischen Verkehrsregister.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 360,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt, planbare monatliche Leasing- und Tilgungsraten.",
        },
        "malus_triggers": {
            "monoculture_pct": 100.0,  # Modena finanziert die eigene Flotte
            "monoculture_originator": "Modena Mobility OÜ",
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 8.5,
            "p2p_empire_safety_band": "Hoch",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": None,
            "lars_wrobbel_rank": "Kein Rating",
        },
    },
    "insoil": {
        "platform": "insoil",
        "platform_name": "InSoil Finance",
        "founding_year": 2023,
        "headquarters": "Vilnius, Litauen",
        "sourcing_strategy": "curated_profile_and_secondary_audits",
        "regulation": {
            "type": "licensed_ecsp",
            "regulator": "Bank of Lithuania (Litauische Zentralbank)",
            "license_number": "ECSP Lizenz Nr. LB002144",
            "custody": "Segregierte Treuhandkonten bei Paysera",
            "investor_compensation": False,
            "contract_structure": "ECSP regulierte Agrar-Hypotheken",
            "notes": "Regulierte ECSP-Plattform unter Aufsicht der Bank of Lithuania.",
        },
        "governance_and_solvency": {
            "guarantor_group": "InSoil Finance UAB",
            "auditor": "Grant Thornton (testiert)",
            "audit_opinion": "Unqualified",
            "profitability": "Spezialisierter Agrarfinanzierer",
            "equity_ratio_pct": 32.0,
            "interest_coverage_ratio": 3.4,
            "notes": "Erfahrenes Team für Agrarökonomie und Bodenbewertung.",
        },
        "collateral_and_workout": {
            "primary_asset_type": "Landwirtschaftlicher Boden und Agrarimmobilien",
            "security_type": "1st-Rank Hypotheken auf Ackerland",
            "ltv_max_pct": 60.0,
            "historical_loss_pct": 0.0,
            "current_npl_pct": 1.0,
            "buyback_grace_period_days": None,
            "notes": "Wertbeständiges Ackerland als erststellige Grundbuchsicherheit mit LTV <= 60 %.",
        },
        "liquidity_and_marketplace": {
            "secondary_market": False,
            "secondary_market_fee_pct": None,
            "secondary_market_waiting_days": None,
            "primary_loan_duration_days_avg": 540,
            "withdrawal_queue_days": 0,
            "notes": "Kein Sekundärmarkt; mittelfristige Bodenfinanzierung (12-24 Monate).",
        },
        "malus_triggers": {
            "monoculture_pct": 15.0,
            "monoculture_originator": None,
            "term_mismatch": False,
            "related_party_opacity": False,
            "distressed_workout": False,
        },
        "benchmarks": {
            "p2p_empire_safety_score": 6.5,
            "p2p_empire_safety_band": "Mittel",
            "p2p_empire_portfolio_perf": 100.0,
            "lars_wrobbel_score": 30,
            "lars_wrobbel_rank": "Rang 5",
        },
    },
}


def main():
    written = 0
    for plat_id, profile in PROFILES.items():
        p_dir = Path("data/platforms") / plat_id
        p_dir.mkdir(parents=True, exist_ok=True)
        p_file = p_dir / "profile.yaml"
        with open(p_file, "w", encoding="utf-8") as f:
            yaml.dump(profile, f, sort_keys=False, allow_unicode=True)
        print(f"✓ Erstellt: {p_file}")
        written += 1
    print(f"\nErfolgreich {written} kuratierte Plattform-Profile geschrieben!")


if __name__ == "__main__":
    main()
